%
% irpVisualizeOBJ can be used to visualize OBJ data generated by
% irpCreateOBJ. As this representation is quite cumbersome it is
% recommended to use the external program "MeshLab" for better
% visualization.

function irpVisualizeOBJ(DataOBJ)

vertices = DataOBJ{1};
faces = DataOBJ{2};

figure,
trimesh(faces,vertices(:,1),vertices(:,2),vertices(:,3));
daspect([1,1,1]);
